### ISSUE TITLE
Website PWA support

### ISSUE THREAD

**Issue by afonsojramos** [franciscobmacedo/frutafeia#4]
Hi @franciscobmacedo!

This is definitely not the right place to do it, but I figured it might be the best one. Feel free to immediately close it if you can't do anything about it. 

Would it be possible to add the required manifest to add support for PWAs?

Thanks,
Afonso Ramos

**Comment by franciscobmacedo** [comment]
Hello! Thanks for the message :) we haven't been working on this project for a while, the code could have a bit of improvement before going ahead and adding new features. What is the purpose of the PWA?

**Comment by afonsojramos** [comment]
The purpose of the PWA is the purpose for all PWAs, you can read more about it [here](https://web.dev/progressive-web-apps/). It should be an easy process as it should be only adding a simple manifest.

**Comment by franciscobmacedo** [comment]
I'm aware of PWAs, but this is a REST API that reads from a Google sheet. It acts more as a serialisation/backup than a proper web app - it depends entirely on the Google sheet itself (you can see it in the API views). I don't understand the point of adding PWA support when there's no frontend here, but maybe I'm missing something?

**Comment by afonsojramos** [comment]
That's what I meant when I said "This is definitely not the right place to do it". I only left this comment here because I had nowhere else to put it, and figured you might be able to forward it to the right place. Feel free to close it otherwise, as obviously that it is not here that it belongs to.

**Comment by franciscobmacedo** [comment]
Right, that's why I said we would need to refactor the code base before being able to do so.

I don't see this happening anytime soon, as this is a tool used solely by Fruta Feia and their own spreadsheet.

If what you're looking for is a version of this app but with a proper web setup, that would probably require a new repo, as this one was done within this [DSSG project](https://www.dssg.pt/en/projects/optimization-of-the-preparation-of-the-weekly-baskets-of-the-northern-hub-of-fruta-feia/) scope.
